const verbs = [
  // ==================================================
  // REGULAR VERBS
  // ==================================================

  {
    id: 1,
    type: "regular",
    infinitive: "answer",
    past: "answered",
    participle: "answered",
    gerund: "answering",
    spanish: "responder",
  },
  {
    id: 2,
    type: "regular",
    infinitive: "arrive",
    past: "arrived",
    participle: "arrived",
    gerund: "arriving",
    spanish: "llegar",
  },
  {
    id: 3,
    type: "regular",
    infinitive: "attend",
    past: "attended",
    participle: "attended",
    gerund: "attending",
    spanish: "asistir",
  },
  {
    id: 4,
    type: "regular",
    infinitive: "belong",
    past: "belonged",
    participle: "belonged",
    gerund: "belonging",
    spanish: "pertenecer",
  },
  {
    id: 5,
    type: "regular",
    infinitive: "burn",
    past: "burned",
    participle: "burned",
    gerund: "burning",
    spanish: "quemar",
  },
  {
    id: 6,
    type: "regular",
    infinitive: "call",
    past: "called",
    participle: "called",
    gerund: "calling",
    spanish: "llamar",
  },
  {
    id: 7,
    type: "regular",
    infinitive: "carry",
    past: "carried",
    participle: "carried",
    gerund: "carrying",
    spanish: "llevar",
  },
  {
    id: 8,
    type: "regular",
    infinitive: "clean",
    past: "cleaned",
    participle: "cleaned",
    gerund: "cleaning",
    spanish: "limpiar",
  },
  {
    id: 9,
    type: "regular",
    infinitive: "close",
    past: "closed",
    participle: "closed",
    gerund: "closing",
    spanish: "cerrar",
  },
  {
    id: 10,
    type: "regular",
    infinitive: "cook",
    past: "cooked",
    participle: "cooked",
    gerund: "cooking",
    spanish: "cocinar",
  },
  {
    id: 11,
    type: "regular",
    infinitive: "copy",
    past: "copied",
    participle: "copied",
    gerund: "copying",
    spanish: "copiar",
  },
  {
    id: 12,
    type: "regular",
    infinitive: "dance",
    past: "danced",
    participle: "danced",
    gerund: "dancing",
    spanish: "bailar",
  },
  {
    id: 13,
    type: "regular",
    infinitive: "discover",
    past: "discovered",
    participle: "discovered",
    gerund: "discovering",
    spanish: "descubrir",
  },
  {
    id: 14,
    type: "regular",
    infinitive: "dress",
    past: "dressed",
    participle: "dressed",
    gerund: "dressing",
    spanish: "vestir",
  },
  {
    id: 15,
    type: "regular",
    infinitive: "earn",
    past: "earned",
    participle: "earned",
    gerund: "earning",
    spanish: "ganar dinero",
  },
  {
    id: 16,
    type: "regular",
    infinitive: "employ",
    past: "employed",
    participle: "employed",
    gerund: "employing",
    spanish: "emplear",
  },
  {
    id: 17,
    type: "regular",
    infinitive: "enjoy",
    past: "enjoyed",
    participle: "enjoyed",
    gerund: "enjoying",
    spanish: "disfrutar",
  },
  {
    id: 18,
    type: "regular",
    infinitive: "enter",
    past: "entered",
    participle: "entered",
    gerund: "entering",
    spanish: "entrar",
  },
  {
    id: 19,
    type: "regular",
    infinitive: "exchange",
    past: "exchanged",
    participle: "exchanged",
    gerund: "exchanging",
    spanish: "intercambiar",
  },
  {
    id: 20,
    type: "regular",
    infinitive: "explain",
    past: "explained",
    participle: "explained",
    gerund: "explaining",
    spanish: "explicar",
  },
  {
    id: 21,
    type: "regular",
    infinitive: "fill",
    past: "filled",
    participle: "filled",
    gerund: "filling",
    spanish: "llenar, completar",
  },
  {
    id: 22,
    type: "regular",
    infinitive: "finish",
    past: "finished",
    participle: "finished",
    gerund: "finishing",
    spanish: "finalizar",
  },
  {
    id: 23,
    type: "regular",
    infinitive: "follow",
    past: "followed",
    participle: "followed",
    gerund: "following",
    spanish: "seguir",
  },
  {
    id: 24,
    type: "regular",
    infinitive: "help",
    past: "helped",
    participle: "helped",
    gerund: "helping",
    spanish: "ayudar",
  },
  {
    id: 25,
    type: "regular",
    infinitive: "invite",
    past: "invited",
    participle: "invited",
    gerund: "inviting",
    spanish: "invitar",
  },
  {
    id: 26,
    type: "regular",
    infinitive: "join",
    past: "joined",
    participle: "joined",
    gerund: "joining",
    spanish: "juntar",
  },
  {
    id: 27,
    type: "regular",
    infinitive: "learn",
    past: "learned",
    participle: "learned",
    gerund: "learning",
    spanish: "aprender",
  },
  {
    id: 28,
    type: "regular",
    infinitive: "like",
    past: "liked",
    participle: "liked",
    gerund: "liking",
    spanish: "gustar",
  },
  {
    id: 29,
    type: "regular",
    infinitive: "listen to",
    past: "listened to",
    participle: "listened to",
    gerund: "listening to",
    spanish: "escuchar",
  },
  {
    id: 30,
    type: "regular",
    infinitive: "live",
    past: "lived",
    participle: "lived",
    gerund: "living",
    spanish: "vivir",
  },
  {
    id: 31,
    type: "regular",
    infinitive: "look at",
    past: "looked at",
    participle: "looked at",
    gerund: "looking at",
    spanish: "mirar",
  },
  {
    id: 32,
    type: "regular",
    infinitive: "love",
    past: "loved",
    participle: "loved",
    gerund: "loving",
    spanish: "amar",
  },
  {
    id: 33,
    type: "regular",
    infinitive: "need",
    past: "needed",
    participle: "needed",
    gerund: "needing",
    spanish: "necesitar",
  },
  {
    id: 34,
    type: "regular",
    infinitive: "open",
    past: "opened",
    participle: "opened",
    gerund: "opening",
    spanish: "abrir",
  },
  {
    id: 35,
    type: "regular",
    infinitive: "play",
    past: "played",
    participle: "played",
    gerund: "playing",
    spanish: "jugar",
  },
  {
    id: 36,
    type: "regular",
    infinitive: "prepare",
    past: "prepared",
    participle: "prepared",
    gerund: "preparing",
    spanish: "preparar",
  },
  {
    id: 37,
    type: "regular",
    infinitive: "publish",
    past: "published",
    participle: "published",
    gerund: "publishing",
    spanish: "publicar",
  },
  {
    id: 38,
    type: "regular",
    infinitive: "rain",
    past: "rained",
    participle: "rained",
    gerund: "raining",
    spanish: "llover",
  },
  {
    id: 39,
    type: "regular",
    infinitive: "receive",
    past: "received",
    participle: "received",
    gerund: "receiving",
    spanish: "recibir",
  },
  {
    id: 40,
    type: "regular",
    infinitive: "remember",
    past: "remembered",
    participle: "remembered",
    gerund: "remembering",
    spanish: "recordar",
  },
  {
    id: 41,
    type: "regular",
    infinitive: "repeat",
    past: "repeated",
    participle: "repeated",
    gerund: "repeating",
    spanish: "repetir",
  },
  {
    id: 42,
    type: "regular",
    infinitive: "rest",
    past: "rested",
    participle: "rested",
    gerund: "resting",
    spanish: "descansar",
  },
  {
    id: 43,
    type: "regular",
    infinitive: "return",
    past: "returned",
    participle: "returned",
    gerund: "returning",
    spanish: "retornar",
  },
  {
    id: 44,
    type: "regular",
    infinitive: "save",
    past: "saved",
    participle: "saved",
    gerund: "saving",
    spanish: "guardar",
  },
  {
    id: 45,
    type: "regular",
    infinitive: "smoke",
    past: "smoked",
    participle: "smoked",
    gerund: "smoking",
    spanish: "fumar",
  },
  {
    id: 46,
    type: "regular",
    infinitive: "spell",
    past: "spelled",
    participle: "spelled",
    gerund: "spelling",
    spanish: "deletrear",
  },
  {
    id: 47,
    type: "regular",
    infinitive: "spoil",
    past: "spoiled",
    participle: "spoiled",
    gerund: "spoiling",
    spanish: "estropear",
  },
  {
    id: 48,
    type: "regular",
    infinitive: "start",
    past: "started",
    participle: "started",
    gerund: "starting",
    spanish: "empezar",
  },
  {
    id: 49,
    type: "regular",
    infinitive: "stop",
    past: "stopped",
    participle: "stopped",
    gerund: "stopping",
    spanish: "detener",
  },
  {
    id: 50,
    type: "regular",
    infinitive: "study",
    past: "studied",
    participle: "studied",
    gerund: "studying",
    spanish: "estudiar",
  },
  {
    id: 51,
    type: "regular",
    infinitive: "talk",
    past: "talked",
    participle: "talked",
    gerund: "talking",
    spanish: "hablar",
  },
  {
    id: 52,
    type: "regular",
    infinitive: "translate",
    past: "translated",
    participle: "translated",
    gerund: "translating",
    spanish: "traducir",
  },
  {
    id: 53,
    type: "regular",
    infinitive: "travel",
    past: "traveled",
    participle: "traveled",
    gerund: "traveling",
    spanish: "viajar",
  },
  {
    id: 54,
    type: "regular",
    infinitive: "type",
    past: "typed",
    participle: "typed",
    gerund: "typing",
    spanish: "tipear",
  },
  {
    id: 55,
    type: "regular",
    infinitive: "visit",
    past: "visited",
    participle: "visited",
    gerund: "visiting",
    spanish: "visitar",
  },
  {
    id: 56,
    type: "regular",
    infinitive: "wait",
    past: "waited",
    participle: "waited",
    gerund: "waiting",
    spanish: "esperar",
  },
  {
    id: 57,
    type: "regular",
    infinitive: "walk",
    past: "walked",
    participle: "walked",
    gerund: "walking",
    spanish: "caminar",
  },
  {
    id: 58,
    type: "regular",
    infinitive: "want",
    past: "wanted",
    participle: "wanted",
    gerund: "wanting",
    spanish: "desear",
  },
  {
    id: 59,
    type: "regular",
    infinitive: "warn",
    past: "warned",
    participle: "warned",
    gerund: "warning",
    spanish: "advertir",
  },
  {
    id: 60,
    type: "regular",
    infinitive: "wash",
    past: "washed",
    participle: "washed",
    gerund: "washing",
    spanish: "lavar",
  },

  // ==================================================
  // IRREGULAR VERBS
  // ==================================================

  {
    id: 61,
    type: "irregular",
    infinitive: "be (am-is-are)",
    past: "was-were",
    participle: "been",
    gerund: "being",
    spanish: "ser o estar",
  },
  {
    id: 62,
    type: "irregular",
    infinitive: "begin",
    past: "began",
    participle: "begun",
    gerund: "beginning",
    spanish: "empezar",
  },
  {
    id: 63,
    type: "irregular",
    infinitive: "break",
    past: "broke",
    participle: "broken",
    gerund: "breaking",
    spanish: "quebrar, romper",
  },
  {
    id: 64,
    type: "irregular",
    infinitive: "bring",
    past: "brought",
    participle: "brought",
    gerund: "bringing",
    spanish: "traer",
  },
  {
    id: 65,
    type: "irregular",
    infinitive: "build",
    past: "built",
    participle: "built",
    gerund: "building",
    spanish: "construir",
  },
  {
    id: 66,
    type: "irregular",
    infinitive: "buy",
    past: "bought",
    participle: "bought",
    gerund: "buying",
    spanish: "comprar",
  },
  {
    id: 67,
    type: "irregular",
    infinitive: "catch",
    past: "caught",
    participle: "caught",
    gerund: "catching",
    spanish: "atrapar",
  },
  {
    id: 68,
    type: "irregular",
    infinitive: "come",
    past: "came",
    participle: "come",
    gerund: "coming",
    spanish: "venir",
  },
  {
    id: 69,
    type: "irregular",
    infinitive: "cost",
    past: "cost",
    participle: "cost",
    gerund: "costing",
    spanish: "costar",
  },
  {
    id: 70,
    type: "irregular",
    infinitive: "cut",
    past: "cut",
    participle: "cut",
    gerund: "cutting",
    spanish: "cortar",
  },
  {
    id: 71,
    type: "irregular",
    infinitive: "do-does",
    past: "did",
    participle: "done",
    gerund: "doing",
    spanish: "hacer",
  },
  {
    id: 72,
    type: "irregular",
    infinitive: "draw",
    past: "drew",
    participle: "drawn",
    gerund: "drawing",
    spanish: "dibujar",
  },
  {
    id: 73,
    type: "irregular",
    infinitive: "dream",
    past: "dreamt",
    participle: "dreamt",
    gerund: "dreaming",
    spanish: "soñar",
  },
  {
    id: 74,
    type: "irregular",
    infinitive: "drink",
    past: "drank",
    participle: "drunk",
    gerund: "drinking",
    spanish: "beber",
  },
  {
    id: 75,
    type: "irregular",
    infinitive: "drive",
    past: "drove",
    participle: "driven",
    gerund: "driving",
    spanish: "manejar, conducir",
  },
  {
    id: 76,
    type: "irregular",
    infinitive: "eat",
    past: "ate",
    participle: "eaten",
    gerund: "eating",
    spanish: "comer",
  },
  {
    id: 77,
    type: "irregular",
    infinitive: "fall down",
    past: "fell down",
    participle: "fallen down",
    gerund: "falling down",
    spanish: "caer",
  },
  {
    id: 78,
    type: "irregular",
    infinitive: "feed",
    past: "fed",
    participle: "fed",
    gerund: "feeding",
    spanish: "alimentar",
  },
  {
    id: 79,
    type: "irregular",
    infinitive: "feel",
    past: "felt",
    participle: "felt",
    gerund: "feeling",
    spanish: "sentir",
  },
  {
    id: 80,
    type: "irregular",
    infinitive: "find",
    past: "found",
    participle: "found",
    gerund: "finding",
    spanish: "encontrar",
  },
  {
    id: 81,
    type: "irregular",
    infinitive: "fly",
    past: "flew",
    participle: "flown",
    gerund: "flying",
    spanish: "volar",
  },
  {
    id: 82,
    type: "irregular",
    infinitive: "get",
    past: "got",
    participle: "got",
    gerund: "getting",
    spanish: "obtener",
  },
  {
    id: 83,
    type: "irregular",
    infinitive: "get up",
    past: "got up",
    participle: "got up",
    gerund: "getting up",
    spanish: "levantar",
  },
  {
    id: 84,
    type: "irregular",
    infinitive: "give",
    past: "gave",
    participle: "given",
    gerund: "giving",
    spanish: "dar",
  },
  {
    id: 85,
    type: "irregular",
    infinitive: "go",
    past: "went",
    participle: "gone",
    gerund: "going",
    spanish: "ir",
  },
  {
    id: 86,
    type: "irregular",
    infinitive: "have/has",
    past: "had",
    participle: "had",
    gerund: "having",
    spanish: "haber, tener",
  },
  {
    id: 87,
    type: "irregular",
    infinitive: "hear",
    past: "heard",
    participle: "heard",
    gerund: "hearing",
    spanish: "oir",
  },
  {
    id: 88,
    type: "irregular",
    infinitive: "hide",
    past: "hid",
    participle: "hidden",
    gerund: "hiding",
    spanish: "esconder",
  },
  {
    id: 89,
    type: "irregular",
    infinitive: "keep",
    past: "kept",
    participle: "kept",
    gerund: "keeping",
    spanish: "mantener",
  },
  {
    id: 90,
    type: "irregular",
    infinitive: "know",
    past: "knew",
    participle: "known",
    gerund: "knowing",
    spanish: "conocer, saber",
  },
  {
    id: 91,
    type: "irregular",
    infinitive: "leave",
    past: "left",
    participle: "left",
    gerund: "leaving",
    spanish: "dejar, irse",
  },
  {
    id: 92,
    type: "irregular",
    infinitive: "lend",
    past: "lent",
    participle: "lent",
    gerund: "lending",
    spanish: "prestar",
  },
  {
    id: 93,
    type: "irregular",
    infinitive: "lose",
    past: "lost",
    participle: "lost",
    gerund: "losing",
    spanish: "perder",
  },
  {
    id: 94,
    type: "irregular",
    infinitive: "make",
    past: "made",
    participle: "made",
    gerund: "making",
    spanish: "hacer, confeccionar",
  },
  {
    id: 95,
    type: "irregular",
    infinitive: "mean",
    past: "meant",
    participle: "meant",
    gerund: "meaning",
    spanish: "significar",
  },
  {
    id: 96,
    type: "irregular",
    infinitive: "meet",
    past: "met",
    participle: "met",
    gerund: "meeting",
    spanish: "encontrar",
  },
  {
    id: 97,
    type: "irregular",
    infinitive: "pay",
    past: "paid",
    participle: "paid",
    gerund: "paying",
    spanish: "pagar",
  },
  {
    id: 98,
    type: "irregular",
    infinitive: "read",
    past: "read",
    participle: "read",
    gerund: "reading",
    spanish: "leer",
  },
  {
    id: 99,
    type: "irregular",
    infinitive: "run",
    past: "ran",
    participle: "run",
    gerund: "running",
    spanish: "correr",
  },
  {
    id: 100,
    type: "irregular",
    infinitive: "say",
    past: "said",
    participle: "said",
    gerund: "saying",
    spanish: "decir",
  },
  {
    id: 101,
    type: "irregular",
    infinitive: "see",
    past: "saw",
    participle: "seen",
    gerund: "seeing",
    spanish: "ver",
  },
  {
    id: 102,
    type: "irregular",
    infinitive: "sell",
    past: "sold",
    participle: "sold",
    gerund: "selling",
    spanish: "vender",
  },
  {
    id: 103,
    type: "irregular",
    infinitive: "send",
    past: "sent",
    participle: "sent",
    gerund: "sending",
    spanish: "enviar",
  },
  {
    id: 104,
    type: "irregular",
    infinitive: "set",
    past: "set",
    participle: "set",
    gerund: "staying",
    spanish: "permanecer",
  },
  {
    id: 105,
    type: "irregular",
    infinitive: "sing",
    past: "sang",
    participle: "sung",
    gerund: "singing",
    spanish: "cantar",
  },
  {
    id: 106,
    type: "irregular",
    infinitive: "sit down",
    past: "sat down",
    participle: "sat down",
    gerund: "sitting",
    spanish: "sentarse",
  },
  {
    id: 107,
    type: "irregular",
    infinitive: "sleep",
    past: "slept",
    participle: "slept",
    gerund: "sleeping",
    spanish: "dormir",
  },
  {
    id: 108,
    type: "irregular",
    infinitive: "speak",
    past: "spoke",
    participle: "spoken",
    gerund: "speaking",
    spanish: "hablar",
  },
  {
    id: 109,
    type: "irregular",
    infinitive: "spend",
    past: "spent",
    participle: "spent",
    gerund: "spending",
    spanish: "pasar tiempo, gastar",
  },
  {
    id: 110,
    type: "irregular",
    infinitive: "steal",
    past: "stole",
    participle: "stolen",
    gerund: "stealing",
    spanish: "robar",
  },
  {
    id: 111,
    type: "irregular",
    infinitive: "swim",
    past: "swam",
    participle: "swum",
    gerund: "swimming",
    spanish: "nadar",
  },
  {
    id: 112,
    type: "irregular",
    infinitive: "take",
    past: "took",
    participle: "taken",
    gerund: "taking",
    spanish: "tomar",
  },
  {
    id: 113,
    type: "irregular",
    infinitive: "teach",
    past: "taught",
    participle: "taught",
    gerund: "teaching",
    spanish: "enseñar",
  },
  {
    id: 114,
    type: "irregular",
    infinitive: "tell",
    past: "told",
    participle: "told",
    gerund: "telling",
    spanish: "contar, relatar",
  },
  {
    id: 115,
    type: "irregular",
    infinitive: "think",
    past: "thought",
    participle: "thought",
    gerund: "thinking",
    spanish: "pensar",
  },
  {
    id: 116,
    type: "irregular",
    infinitive: "understand",
    past: "understood",
    participle: "understood",
    gerund: "understanding",
    spanish: "entender",
  },
  {
    id: 117,
    type: "irregular",
    infinitive: "wake up",
    past: "woke up",
    participle: "woken up",
    gerund: "waking up",
    spanish: "despertar",
  },
  {
    id: 118,
    type: "irregular",
    infinitive: "wear",
    past: "wore",
    participle: "worn",
    gerund: "wearing",
    spanish: "llevar puesto",
  },
  {
    id: 119,
    type: "irregular",
    infinitive: "win",
    past: "won",
    participle: "won",
    gerund: "winning",
    spanish: "ganar",
  },
  {
    id: 120,
    type: "irregular",
    infinitive: "write",
    past: "wrote",
    participle: "written",
    gerund: "writing",
    spanish: "escribir",
  },
];
